[package]
name = "ping-pong-bench-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[build-dependencies]
ping-pong-bench-app = { path = "../app" }
sails-client-gen.workspace = true
# TODO: Switch to new IDL generator crate
# sails-idl-gen.workspace = true
