[package]
name = "sails-macros-core"
description = "Implementations of procedural macros for the Sails framework"
documentation = "https://docs.rs/sails-macros-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
convert_case.workspace = true
parity-scale-codec.workspace = true
proc-macro-error.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full", "extra-traits"] }

[dev-dependencies]
insta.workspace = true
prettyplease.workspace = true

[features]
ethexe = []
