[package]
name = "sails-sol-gen"
description = "Solidity contract generator for the Sails framework"
documentation = "https://docs.rs/sails-sol-gen"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
sails-idl-parser-v2.workspace = true
handlebars.workspace = true
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
sails-idl-meta.workspace = true
convert_case.workspace = true

[dev-dependencies]
insta.workspace = true
