[package]
name = "rmrk-catalog"
version = "0.1.0"
edition = "2021"

[dependencies]
gstd.workspace = true
sails-exec-context-gstd.workspace = true
rmrk-catalog-app = { path = "../app" }

[build-dependencies]
gwasm-builder.workspace = true
sails-idlgen.workspace = true
