[package]
name = "rmrk-catalog"
version = "0.1.0"
edition.workspace = true

[dependencies]
rmrk-catalog-app = { path = "../app" }

[build-dependencies]
# TODO: Switch to new IDL generator crate
# sails-idl-gen.workspace = true
sails-rs = { workspace = true, features = ["build"] }
rmrk-catalog-app = { path = "../app" }                       # Used for generating IDL (service metadata)
