[package]
name = "rmrk-catalog"
version = "0.1.0"
edition = "2021"

[dependencies]
rmrk-catalog-app = { path = "../app" }

[build-dependencies]
rmrk-catalog-app = { path = "../app" } # Used for generating IDL (service metadata)
sails-builder.workspace = true
