[package]
name = "redirect-client"
version = "0.1.0"
edition.workspace = true

[dependencies]
sails-rs.workspace = true

[build-dependencies]
redirect-app = { path = "../app" }
sails-rs = { workspace = true, features = ["build"] }
sails-client-gen.workspace = true
