[package]
name = "puppeteer-svc"
version = "0.1.0"
edition = "2021"

[dependencies]
gstd.workspace = true
sails-rtl.workspace = true
puppeteer-app = { path = "../app" }

[build-dependencies]
sails-builder.workspace = true
sails-idl-gen.workspace = true
puppeteer-app = { path = "../app" }
