[package]
name = "this-that-svc-app"
version = "0.1.0"
edition = "2021"

[dependencies]
gstd = { workspace = true, features = ["debug"] }
sails-rtl.workspace = true
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
