[package]
name = "sails-build-support"
description = "Shared build-time helpers for Sails programs"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
cargo_metadata.workspace = true
camino.workspace = true
serde-json.workspace = true
toml_edit.workspace = true
blake3.workspace = true
sails-interface-id.workspace = true
sails-idl-meta.workspace = true
rustdoc-types.workspace = true
log.workspace = true
once_cell.workspace = true
