[package]
name = "redirect-proxy"
version = "0.1.0"
edition.workspace = true

[package.metadata.sails]
skip-manifest-check = true

[dependencies]
sails-rs.workspace = true
redirect-client = { path = "../client" }

[build-dependencies]
sails-rs = { workspace = true, features = ["wasm-builder"] }
