[package]
name = "sails-idl-parser"
description = "IDL parser for the Sails framework"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lalrpop-util.workspace = true
logos.workspace = true
thiserror.workspace = true

[build-dependencies]
lalrpop.workspace = true

[dev-dependencies]
itertools.workspace = true
