[package]
name = "{{ app-project-name }}"
version = "0.1.0"
edition = "2024"

[dependencies]
sails-rs = "{{ sails-rs-version }}"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sails-rs = { version = "{{ sails-rs-version }}", features = ["std"] }
