[package]
name = "demo-walker"
version = "0.1.0"
edition.workspace = true

[package.metadata.sails]
services = ["demo_walker::WalkerService"]

[dependencies]
sails-rs = { workspace = true }
anyhow = { workspace = true, optional = true }
sails-build = { workspace = true, optional = true }

[build-dependencies]
sails-rs = { workspace = true, features = ["wasm-builder"] }
sails-build.workspace = true

[features]
default = ["sails-canonical"]
sails-canonical = []
sails-meta-dump = ["sails-canonical", "dep:anyhow", "dep:sails-build"]

[[bin]]
name = "sails_meta_dump"
path = "src/bin/sails_meta_dump.rs"
required-features = ["sails-meta-dump"]
