[package]
name = "sails-client-gen"
description = "Rust client generator for the Sails framework"
documentation = "https://docs.rs/sails-client-gen"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
convert_case.workspace = true
genco.workspace = true
parity-scale-codec.workspace = true
sails-idl-parser-v2.workspace = true

[dev-dependencies]
insta.workspace = true
