[package]
name = "sails-idl-parser-v2"
description = "IDL v2 parser for the Sails framework"
documentation = "https://docs.rs/sails-idl-parser"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["rlib"]

[features]
default = []
std = ["pest/std", "pest_derive/std", "thiserror/std"]

[dependencies]
thiserror.workspace = true
pest.workspace = true
pest_derive.workspace = true
sails-idl-meta = { workspace = true, features = ["ast"] }
paste.workspace = true
