[package]
name = "sails-idl-parser-v2"
description = "IDL v2 parser for the Sails framework"
documentation = "https://docs.rs/sails-idl-parser"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["std"]
std = ["anyhow/std", "pest/std", "pest_derive/std"]

[dependencies]
anyhow = { version = "1", default-features = false }
pest = { version = "2", default-features = false }
pest_derive = { version = "2", default-features = false }
sails-idl-meta = { workspace = true, features = ["ast"] }
paste.workspace = true
hashbrown = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
dlmalloc = { version = "0.2", features = ["global"] }

[[test]]
name = "full_coverage_visitor_test"
required-features = ["std"]

[[test]]
name = "post_process"
required-features = ["std"]