[package]
name = "sails-idl-gen"
description = "IDL generator for the Sails framework"
documentation = "https://docs.rs/sails-idl-gen"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
askama.workspace = true
convert_case.workspace = true
gprimitives.workspace = true
sails-idl-meta = { workspace = true, features = ["ast", "templates"] }
scale-info = { workspace = true, features = ["derive", "docs", "serde"] }
serde = { workspace = true, features = ["derive"] }
serde-json.workspace = true
thiserror.workspace = true
syn = { workspace = true, features = ["parsing", "full", "fold"] }
quote.workspace = true

[dev-dependencies]
insta.workspace = true
sails-idl-parser.workspace = true
